const fs = require('fs');
const { execSync } = require('child_process');

// Get the git hash or tag
let version = execSync('git describe --tags --always').toString().trim();

// Check for uncommitted changes to tracked files
// --no-ext-diff: don't use external diff tools
// --quiet: exit with code 1 if there are changes
// This only checks tracked files (ignores untracked)
try {
  execSync('git diff --no-ext-diff --quiet', { stdio: 'ignore' });
  // No changes in working directory
} catch (error) {
  // There are uncommitted changes to tracked files
  version += '-wip';
}

// Also check for staged but uncommitted changes
try {
  execSync('git diff --no-ext-diff --cached --quiet', { stdio: 'ignore' });
  // No staged changes
} catch (error) {
  // There are staged changes
  if (!version.endsWith('-wip')) {
    version += '-wip';
  }
}

const content = `// This file is automatically generated by generate-version.js
export const version = '${version}';
`;

fs.writeFileSync('src/environments/version.ts', content);
console.log(`Generated version: ${version}`);
