const fs = require('fs');
const { execSync } = require('child_process');

const version = execSync('git describe --tags --always').toString().trim();

const content = `// This file is automatically generated by generate-version.js
export const version = '${version}';
`;

fs.writeFileSync('src/environments/version.ts', content);
